#!/bin/bash -x

#
# Copyright (C) 2022 Nethesis S.r.l.
# http://www.nethesis.it - nethserver@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see COPYING.
#

# No migration required
if [ ! -f config.json ]; then
    exit 0
fi

# Prepare database initialization
cat <<EOF > restore/zz_stop.sh
#!/bin/sh

killall postgres
EOF
chmod a+x restore/zz_stop.sh

# Execute database restore
# The cointainer will be stopped at the end
/usr/bin/podman run --rm --replace --name postgres-app --env-file=$HOME/.config/state/environment \
    --volume postgres-data:/var/lib/postgresql/data:Z \
    --volume  $HOME/.config/state/restore/:/docker-entrypoint-initdb.d/:Z \
    --env POSTGRES_USER=mattuser \
    --env POSTGRES_PASSWORD=Nethesis,1234 \
    --env POSTGRES_DB=mattermost \
    --env TZ=UTC \
    ${POSTGRES_IMAGE}

# Cleanup database data
rm -f restore/zz_stop.sh restore/dump.sql

# Start services
systemctl --user start mattermost

# Wait a bit for container initialization
sleep 5


# Wait for the container
while ! podman ps | grep -q mattermost-app
do
    echo "Waiting for mattermost-app"
    sleep 1
done

# Wait a bit for container initialization
sleep 2

# Copy the new config file and make it writable
podman cp --archive config.json mattermost-app:/mattermost/config/config.json
podman exec mattermost-app chown -R mattermost:mattermost /mattermost/config/


# Cleanup migration data
rm -f config.json
