#!/bin/bash

#
# Copyright (C) 2024 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# redirect the standard output  to the standard error
exec 1>&2

# check upgrade requirement : https://docs.mattermost.com/upgrade/important-upgrade-notes.html
# fix for database upgrade from 8.1.13 to 9.11.0

# test if the postgres-app is active
if ! systemctl is-active -q --user postgres-app.service; then
    echo "Postgres service is not active, exiting"
    exit 0
fi

echo "Postgres service is active, we start database upgrade to 9.11.0"

podman exec -i postgres-app bash -c '
PGPASSWORD="Nethesis,1234" psql -U mattuser -d mattermost -c "
CREATE TABLE IF NOT EXISTS retentionidsfordeletion (
    id varchar(26) PRIMARY KEY,
    tablename varchar(64),
    ids varchar(26)[]
);
CREATE INDEX IF NOT EXISTS idx_retentionidsfordeletion_tablename ON retentionidsfordeletion (tablename);
"'
